[package]
name = "bevy_stylebox"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = {workspace = true, default-features = false}

[features]
basis-universal = ["bevy/basis-universal"]
